-- Secret Santa Database Schema
-- Run this SQL in the Supabase SQL Editor to create the tables

-- Groups table
CREATE TABLE groups (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Participants table
CREATE TABLE participants (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL
);

-- Pairs table (Secret Santa assignments)
CREATE TABLE pairs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  giver_id BIGINT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  receiver_id BIGINT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  viewed_at TIMESTAMPTZ DEFAULT NULL
);

-- Para adicionar a coluna em tabelas existentes:
-- ALTER TABLE pairs ADD COLUMN viewed_at TIMESTAMPTZ DEFAULT NULL;

-- Create indexes for better query performance
CREATE INDEX idx_participants_group_id ON participants(group_id);
CREATE INDEX idx_pairs_group_id ON pairs(group_id);
CREATE INDEX idx_pairs_giver_id ON pairs(giver_id);
CREATE INDEX idx_groups_code ON groups(code);
